import {CharKey, Resources} from "../types";
import {resoursePaths} from "../resourse-paths";
import {rndBetween} from "../utils/utils-math";
import {AtlasKey} from "../utils/utils-types";

type CharTemplate = {
    name: string,
    hp: number,
    morale: number,
    moralePrice: number,
    dmg: number,
    createResources: () => Resources
    isCombatant: boolean,
    atlasKey: AtlasKey,
    canCounterAttack?: boolean,
    isDefender?: boolean,
    isRanged?: boolean,
    isMounted?: boolean
}

export const charConfig: {[key: string]: CharTemplate} = {
    [CharKey.FARMER]: {
        name: 'chars.peasant',
        hp: 10,
        morale: 20,
        moralePrice: 10,
        dmg: 1,
        createResources: (): Resources => ({gold: rndBetween(1, 400), food: rndBetween(1, 4)}),
        isCombatant: true,
        atlasKey: 'peasant',
        canCounterAttack: false,
        isDefender: false,
        isRanged: false,
    },

    [CharKey.MILITIA]: {
        name: 'chars.militia',
        hp: 15,
        morale: 30,
        moralePrice: 15,
        dmg: 2,
        createResources: (): Resources => ({gold: 1, food: 1}),
        isCombatant: true,
        atlasKey: 'pikeman',
        canCounterAttack: true,
        isDefender: false,
        isRanged: false,
    },

    [CharKey.ARCHER]: {
        name: 'chars.archer',
        hp: 30,
        morale: 30,
        moralePrice: 15,
        dmg: 2,
        createResources: (): Resources => ({gold: 1, food: 1}),
        isCombatant: true,
        atlasKey: 'archer',
        canCounterAttack: false,
        isDefender: false,
        isRanged: true,
    },

    [CharKey.SHIELDMAN]: {
        name: 'chars.shieldman',
        hp: 20,
        morale: 100,
        moralePrice: 25,
        dmg: 6,
        createResources: (): Resources => ({gold: 1, food: 1}),
        isCombatant: true,
        atlasKey: 'shieldman',
        canCounterAttack: false,
        isDefender: true,
        isRanged: false,
    },
    [CharKey.KNIGHT]: {
        name: 'chars.knight',
        hp: 30,
        morale: 300,
        moralePrice: 50,
        dmg: 8,
        createResources: (): Resources => ({gold: 1, food: 1}),
        isCombatant: true,
        atlasKey: 'knight',
        isMounted: true,
    },


    //
    //
    //
    //
    // [CharKey.ARISTOCRAT]: {
    //     name: 'chars.aristocrat',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.CARRIAGE]: {
    //     name: 'chars.carriage',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.CHILD]: {
    //     name: 'chars.child',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.DONKEY]: {
    //     name: 'chars.donkey',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.FARMER_WOMEN]: {
    //     name: 'chars.peasant_women',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.KING]: {
    //     name: 'chars.king',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.PRINCE]: {
    //     name: 'chars.price',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: true,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.PRINCESS]: {
    //     name: 'chars.princess',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.TRADE_CART]: {
    //     name: 'chars.trade_card',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.TRADER]: {
    //     name: 'chars.trader',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },

}