import {CharKey, Resources} from "./types";
import {resoursePaths} from "./resourse-paths";

// PEASANT_HP = 10,
// PEASANT_WILL = 20,
// PEASANT_WILL_PRICE = 10,
// PEASANT_DEX = 2,
// PEASANT_STR = 1,
//
// PIKEMAN_HP = 15,
// PIKEMAN_WILL = 30,
// PIKEMAN_WILL_PRICE = 15,
// PIKEMAN_STR = 2,
// PIKEMAN_DEX = 4,
//
// SHIELDMAN_HP = 20,
// SHIELDMAN_WILL = 100,
// SHIELDMAN_WILL_PRICE = 25,
// SHIELDMAN_STR = 6,
// SHIELDMAN_DEX = 4,
//
// KNIGHT_HP = 30,
// KNIGHT_WILL = 300,
// KNIGHT_WILL_PRICE = 50,
// KNIGHT_STR = 8,
// KNIGHT_STR_LOW = 6,
// KNIGHT_DEX = 8,
// KNIGHT_DEX_LOW = 6,

export const charTemplates = {
    [CharKey.FARMER]: {
        name: 'chars.peasant',
        hp: 10,
        morale: 20,
        moralePrice: 10,
        dmg: 1,
        createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
        isCombatant: true,
        animationsPath: resoursePaths.atlases.peasant,
    },

    [CharKey.MILITIA]: {
        name: 'chars.militia',
        hp: 15,
        morale: 30,
        moralePrice: 15,
        dmg: 2,
        createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
        isCombatant: true,
        animationsPath: resoursePaths.atlases.militia,
    },

    [CharKey.SOLDIER]: {
        name: 'chars.soldier',
        hp: 20,
        morale: 100,
        moralePrice: 25,
        dmg: 6,
        createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
        isCombatant: true,
        animationsPath: resoursePaths.atlases.soldier,
    },
    [CharKey.KNIGHT]: {
        name: 'chars.knight',
        hp: 30,
        morale: 300,
        moralePrice: 50,
        dmg: 8,
        createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
        isCombatant: true,
        animationsPath: resoursePaths.atlases.knight,
    },


    //
    //
    //
    //
    // [CharKey.ARISTOCRAT]: {
    //     name: 'chars.aristocrat',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.CARRIAGE]: {
    //     name: 'chars.carriage',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.CHILD]: {
    //     name: 'chars.child',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.DONKEY]: {
    //     name: 'chars.donkey',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.FARMER_WOMEN]: {
    //     name: 'chars.peasant_women',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.KING]: {
    //     name: 'chars.king',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.PRINCE]: {
    //     name: 'chars.price',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: true,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.PRINCESS]: {
    //     name: 'chars.princess',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.TRADE_CART]: {
    //     name: 'chars.trade_card',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },
    // [CharKey.TRADER]: {
    //     name: 'chars.trader',
    //     hp: 10,
    //     morale: 10,
    //     moralePrice: 10,
    //     dmg: 1,
    //     createResources: (): Resources => ({gold: 1, materials: 1, food: 1}),
    //     isCombatant: false,
    //     animationsPath: resoursePaths.atlases.peasant,
    // },

}